### ISSUE TITLE
Commands do not work on server; crashes in singleplayer

### ISSUE THREAD

**Issue by Lieutenant2014** [samueljtaylor/TaylorCommands#3]
[crash-2020-05-01_16.26.14-server.txt](https://github.com/samueljtaylor/TaylorCommands/files/4566174/crash-2020-05-01_16.26.14-server.txt)
[crash-2020-05-01_16.21.16-server.txt](https://github.com/samueljtaylor/TaylorCommands/files/4566175/crash-2020-05-01_16.21.16-server.txt)
These first two are from my single player attempts, and also show me joining my server.
[latest.log](https://github.com/samueljtaylor/TaylorCommands/files/4566177/latest.log)
And the latest.log is from my server. I'm not entirely certain what is happening, but The commands simply do not work, and the chat tells me that the command is invalid. This is from the latest version of your mod.
And whenever I attempt to load up a singleplayer world, it just crashes.

**Comment by samueljtaylor** [comment]
Hi @Lieutenant2014 

I'll make a release for 20w18a, It looks like that's really the only thing that would be causing that issue.

**Comment by samueljtaylor** [comment]
I've published a release for 20w18a you can download from [curseforge](https://www.curseforge.com/minecraft/mc-mods/taylorcommands/files/all) or [github releases](https://github.com/samueljtaylor/TaylorCommands/releases)

Let me know if there's any issues
