### ISSUE TITLE
In singleplayer, homes and warps are saved in the game folder instead of the world folder

### ISSUE THREAD

**Issue by Purpzie** [samueljtaylor/TaylorCommands#6]
This causes homes and warps to carry over into other worlds where they may not always make sense.

![image](https://user-images.githubusercontent.com/25022704/123717089-ba007c80-d841-11eb-9b2d-82f7ee690e07.png)

I don't make fabric mods, but I assume there is a better way to get the config location than this?

https://github.com/samueljtaylor/TaylorCommands/blob/e31ea6afcd0b9a807cf1c2dccd7be38b1b90761d/src/main/java/ca/samueltaylor/taylor_commands/TaylorCommands.java#L145-L147

Just a note, this is in 1.17 using the build artifact from [here](https://github.com/samueljtaylor/TaylorCommands/actions/runs/976630832).

**Comment by samueljtaylor** [comment]
Thanks for the issue @Purpzie 

Yeah that's definitely a problem - I haven't really kept up with this but I'll be working on a rewrite to fix a number of things.

**Comment by samueljtaylor** [comment]
Hi @Purpzie 

I have released a new version after rewriting the mod. It addresses that issue.

[Release](https://github.com/samueljtaylor/SimpleCommands/releases/tag/1.0.0-1.17)

Let me know if you run into any other issues, thanks!
